url: https://twocupsofchaa.com
baseurl: 

# Site settings
title: Two Cups of Chaa
email: me@twocupsofchaa.com
description: "Coming Soon..."


# Team names, titles and social links
people:
- name: Neera Datta
  pic: 
  position: Owner
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/twocupsofchaa
  - title: instagram
    url: https://www.instagram.com/twocupsofchaa/
  - title: pinterest
    url: https://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: https://bitbucket.org/jekyll
  - title: github
    url: https://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Somewhere

# Build settings
markdown: kramdown
permalink: pretty